# fly.toml app configuration file generated for digitalviolence on 2025-01-27T15:30:00+09:00
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'digitalviolence'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  interval = "15s"
  timeout = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/"
  protocol = "http"
  restart_limit = 0
  headers = {}

[vm]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[mounts]]
  source = 'digitalviolence_data'
  destination = '/app/data'

[env]
  PORT = '8080'
  PYTHONPATH = '/app'

[deploy]
  release_command = 'echo "Starting deployment..."'
